spring.application.name=inno-user-service

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate



spring.cache.redis.time-to-live=600000
spring.cache.redis.key-prefix=user_service:
spring.cache.redis.cache-null-values=false
